name: CI

on: [pull_request]

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        with:
          args: analyse src
  tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, ctype, iconv, intl
          ini-values: pcov.directory=src
          coverage: pcov
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install --no-suggest --no-progress --prefer-dist
